version: "3.9"

services:
  ${SERVICE_NAME}:
    build:
      context: .
      dockerfile: ${DOCKERFILE_NAME}
    stdin_open: true
    tty: true
    user: ${CONTAINER_USER}
    env_file:
      - .env
    volumes:
      - ./config/gcloud-service-account.json.json:/config/gcloud-service-account.json
      - ./nix/nix.conf:${WORKING_DIR}/.config/nix/nix.conf
      - ./entrypoint/:${WORKING_DIR}/entrypoint/
      - ./nix/:${WORKING_DIR}/nix/
      - ./images:/images
